---
categories:
- Organisational Structure
- Human Resources
description: Welcome to the organisational chart of Tessera, designed to elucidate the structural hierarchy and functional divisions within our company.
title: Org Chart
---

|              |                                     |
|--------------|-------------------------------------|
| **Title**    | Org Chart             |
| **Doc#**     | DOC-HUMA-000 |
| **Version**  | 1.0                                 |
| **Date**     | 19-06-2023                              |

Welcome to the organisational chart of Tessera, designed to elucidate
the structural hierarchy and functional divisions within our company. This chart
serves as a visual guide to understand the roles and reporting relationships
that drive the efficiency and decision-making processes at Tessera.

In this organisational chart, you will find:

- **Executive Leadership**: Showcasing our top management, including the CEO,
  CFO, and CTO, who lead the strategic direction and oversight of the company.
- **Departmental Structure**: Detailed breakdown of our core departments such as
  Engineering, IT, Compliance, Cloud Operations, People & Culture, and Finance,
  along with their respective heads and teams.
- **Reporting Lines**: Clearly marked lines indicate who reports to whom,
  highlighting the flow of accountability and communication within the company.
- **Support and Administrative Roles**: These roles are depicted to show their
  support to multiple departments, reinforcing the backbone of our corporate
  operations.
- **Strategic Units**: Special project teams or innovation units that work on
  advanced developments to keep our services at the technological forefront.

This organisational chart is an invaluable tool for both current and prospective
employees, providing a clear picture of our company’s reporting structure and
operational dynamics. It is designed to help familiarise you with our team and
to foster an understanding of how various roles and departments interact to
achieve common goals within Tessera.

```{mermaid}
graph TD
    CEO[Henrik Larsson<br/>CEO] --> CTO
    CEO --> CIO
    CEO --> COO
    CEO --> CFO
    CEO --> CISO

    CTO[Dr Sana Qureshi<br/>CTO] --> Eng[Noah Bennett<br/>Head of Engineering]
    CTO --> Arch[Connor Hayes<br/>Cloud Infrastructure Architect]

    CIO[Adrian Vasquez<br/>CIO] --> IT[Hamish Boyd<br/>Head of IT]

    CISO[Isabella Ferreira<br/>CISO] --> Comp[Margaux Dubois<br/>Head of Compliance]

    COO[Grace Sullivan<br/>COO] --> Ops[Rafa Costa<br/>Cloud Service Operations]
    COO --> People[Anika Desai<br/>Head of People]

    CFO[Priya Nair<br/>CFO] --> Finance[Finance &amp; Accounting]
```